# Generated by Django 6.0.2 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rustdesdevice_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='peers',
            field=models.TextField(verbose_name='机器ID列表'),
        ),
    ]
